name: Arch Linux PKGBUILD builder
description: Builds and validates PKGBUILD definition

branding:
  icon: triangle
  color: blue

inputs:
  pkgbuild_dir:
    description: >-
      Path to Directory containing the PKGBUILD file
    required: false
    default: '.'
  target:
    description: >-
      Validation target.
      Can be one of: "pkgbuild", "srcinfo", "run"
    required: false
    default: 'pkgbuild'
  command:
    description: >-
      Command to run after package installation.
      Used when target=run
    required: false
  debug:
    description: Turns debugging on
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.pkgbuild_dir }}
    - ${{ inputs.target }}
    - ${{ inputs.command }}
    - ${{ inputs.debug }}
